# Inserted into the MAIN_PAGE_URL in 'main.py' for specific data collection
YEAR = 2024
PREVIOUS_YEAR = 2023
Q1 = 1
Q2 = 2
Q3 = 3
Q4 = 4

# Reporting Period Dates
reporting_periods = {
    'Q1': [f'{PREVIOUS_YEAR}-04-01', f'{PREVIOUS_YEAR}-06-30'],
    'Q2': [f'{PREVIOUS_YEAR}-07-01', f'{PREVIOUS_YEAR}-09-30'],
    'Q3': [f'{PREVIOUS_YEAR}-10-01', f'{PREVIOUS_YEAR}-12-31'],
    'Q4': [f'{YEAR}-01-01', f'{YEAR}-03-31']
}

REPORTING_TIME_PERIOD = reporting_periods['Q4']
FISCAL_QUARTER = Q4



# URL Information
 # MP_EXPENSES_PAGE_URL needs to have /YEAR/QUARTER/ + unique href value appended to it
BASE_URL = 'https://www.ourcommons.ca'
MP_EXPENSES_PAGE_URL = f"{BASE_URL}/proactivedisclosure/en/members/{YEAR}/{Q4}/"


# Firefox/Selenium Constants
FIREFOX_BINARY = '/opt/firefox/firefox'
GECKO_DRIVER_EXECUTABLE = '/usr/local/bin/geckodriver'



# Error Messages
NO_TBODY_FOUND = 'No <tbody> element found in the HTML'


# Tbody classes
EXPENSES_MAIN_INFO = 'expenses-main-info'


# General Strings
EMPTY_STRING = ''
NOT_LISTED = 'Not Listed'



# MP Lookup Dict
MP_LOOKUP = {
    'Ziad Aboultaif': 1,
    'Scott Aitchison': 2,
    'Dan Albas': 3,
    'John Aldag': 4,
    'Omar Alghabra': 5,
    'Shafqat Ali': 6,
    'Dean Allison': 7,
    'Anita Anand': 8,
    'Gary Anandasangaree': 9,
    'Charlie Angus': 10,
    'Mel Arnold': 11,
    'René Arseneault': 12,
    'Chandra Arya': 13,
    'Niki Ashton': 14,
    'Jenica Atwin': 15,
    'Taylor Bachrach': 16,
    'Vance Badawey': 17,
    'Parm Bains': 18,
    'Yvan Baker': 19,
    'Tony Baldinelli': 20,
    'John Barlow': 21,
    'Michael Barrett': 22,
    'Lisa Marie Barron': 23,
    'Xavier Barsalou-Duval': 24,
    'Jaime Battiste': 25,
    'James Bezan': 26,
    'Marie-Claude Bibeau': 27,
    'Chris Bittle': 28,
    'Daniel Blaikie': 29,
    'Bill Blair': 30,
    'Yves-François Blanchet': 31,
    'Maxime Blanchette-Joncas': 32,
    'Rachel Blaney': 33,
    'Kelly Block': 34,
    'Kody Blois': 35,
    'Randy Boissonnault': 36,
    'Alexandre Boulerice': 37,
    'Valerie Bradford': 38,
    'Richard Bragdon': 39,
    'John Brassard': 40,
    'Élisabeth Brière': 41,
    'Larry Brock': 42,
    'Alexis Brunelle-Duceppe': 43,
    'Blaine Calkins': 44,
    'Richard Cannings': 45,
    'Frank Caputo': 46,
    'Ben Carr': 47,
    'Colin Carrie': 48,
    'Sean Casey': 49,
    'Louise Chabot': 50,
    'Bardish Chagger': 51,
    'George Chahal': 52,
    'Adam Chambers': 53,
    'François-Philippe Champagne': 54,
    'Martin Champoux': 55,
    'Sophie Chatel': 56,
    'Shaun Chen': 57,
    'Paul Chiang': 58,
    'Michael Chong': 59,
    'Chad Collins': 60,
    'Laurel Collins': 61,
    'Michael Cooper': 62,
    'Serge Cormier': 63,
    'Michael Coteau': 64,
    'Gérard Deltell': 65,
    'Luc Desilets': 66,
    'Blake Desjarlais': 67,
    'Sukh Dhaliwal': 68,
    'Anju Dhillon': 69,
    'Lena Metlege Diab': 70,
    'Todd Doherty': 71,
    'Han Dong': 72,
    'Terry Dowdall': 73,
    'Earl Dreeshen': 74,
    'Francis Drouin': 75,
    'Emmanuel Dubourg': 76,
    'Jean-Yves Duclos': 77,
    'Terry Duguid': 78,
    'Eric Duncan': 79,
    'Kirsty Duncan': 80,
    'Julie Dzerowicz': 81,
    'Ali Ehsassi': 82,
    'Fayçal El-Khoury': 83,
    'Stephen Ellis': 84,
    'Dave Epp': 85,
    'Nathaniel Erskine-Smith': 86,
    'Rosemarie Falk': 87,
    'Ted Falk': 88,
    'Ed Fast': 89,
    'Greg Fergus': 90,
    'Michelle Ferreri': 91,
    'Andy Fillmore': 92,
    'Kerry-Lynne Findlay': 93,
    'Darren Fisher': 94,
    'Peter Fonseca': 95,
    'Mona Fortier': 96,
    'Rhéal Éloi Fortin': 97,
    'Peter Fragiskatos': 98,
    'Sean Fraser': 99,
    'Chrystia Freeland': 100,
    'Hedy Fry': 101,
    'Iqwinder Gaheer': 102,
    'Anna Gainey': 103,
    'Cheryl Gallant': 104,
    'Jean-Denis Garon': 105,
    'Randall Garrison': 106,
    'Marie-Hélène Gaudreau': 107,
    'Leah Gazan': 108,
    'Garnett Genuis': 109,
    'Mark Gerretsen': 110,
    'Marilène Gill': 111,
    'Marilyn Gladu': 112,
    'Joël Godin': 113,
    'Laila Goodridge': 114,
    'Karina Gould': 115,
    'Jacques Gourde': 116,
    'Tracy Gray': 117,
    'Matthew Green': 118,
    'Steven Guilbeault': 119,
    'Patty Hajdu': 120,
    'Jasraj Singh Hallan': 121,
    'Brendan Hanley': 122,
    'Ken Hardie': 123,
    'Lisa Hepfner': 124,
    'Randy Hoback': 125,
    'Mark Holland': 126,
    'Anthony Housefather': 127,
    'Carol Hughes': 128,
    'Ahmed Hussen': 129,
    'Gudie Hutchings': 130,
    'Angelo Iacono': 131,
    'Lori Idlout': 132,
    'Marci Ien': 133,
    'Helena Jaczek': 134,
    'Matt Jeneroux': 135,
    'Gord Johns': 136,
    'Mélanie Joly': 137,
    'Yvonne Jones': 138,
    'Arielle Kayabaga': 139,
    'Mike Kelloway': 140,
    'Pat Kelly': 141,
    'Iqra Khalid': 142,
    'Arpan Khanna': 143,
    'Kamal Khera': 144,
    'Robert Kitchen': 145,
    'Tom Kmiec': 146,
    'Annie Koutrakis': 147,
    'Michael Kram': 148,
    'Shelby Kramp-Neuman': 149,
    'Damien Kurek': 150,
    'Stephanie Kusie': 151,
    'Irek Kusmierczyk': 152,
    'Jenny Kwan': 153,
    'Mike Lake': 154,
    'Marie-France Lalonde': 155,
    'Emmanuella Lambropoulos': 156,
    'David Lametti': 157,
    'Kevin Lamoureux': 158,
    'Melissa Lantsman': 159,
    'Viviane LaPointe': 160,
    'Andréanne Larouche': 161,
    'Patricia Lattanzio': 162,
    'Stéphane Lauzon': 163,
    'Philip Lawrence': 164,
    'Dominic LeBlanc': 165,
    'Diane Lebouthillier': 166,
    'Richard Lehoux': 167,
    'Sébastien Lemire': 168,
    'Branden Leslie': 169,
    'Chris Lewis': 170,
    'Leslyn Lewis': 171,
    'Ron Liepert': 172,
    'Joël Lightbound': 173,
    'Dane Lloyd': 174,
    'Ben Lobb': 175,
    'Wayne Long': 176,
    'Lloyd Longfield': 177,
    'Tim Louis': 178,
    'Lawrence MacAulay': 179,
    'Heath MacDonald': 180,
    'Alistair MacGregor': 181,
    'Steven MacKinnon': 182,
    'Larry Maguire': 183,
    'Shuvaloy Majumdar': 184,
    'James Maloney': 185,
    'Richard Martel': 186,
    'Soraya Martinez Ferrada': 187,
    'Brian Masse': 188,
    'Lindsay Mathyssen': 189,
    'Bryan May': 190,
    'Elizabeth May': 191,
    'Dan Mazier': 192,
    'Kelly McCauley': 193,
    'Ken McDonald': 194,
    'David McGuinty': 195,
    'John McKay': 196,
    'Ron McKinnon': 197,
    'Greg McLean': 198,
    'Michael McLeod': 199,
    'Heather McPherson': 200,
    'Eric Melillo': 201,
    'Alexandra Mendès': 202,
    'Marco Mendicino': 203,
    'Wilson Miao': 204,
    'Kristina Michaud': 205,
    'Marc Miller': 206,
    'Rob Moore': 207,
    'Marty Morantz': 208,
    'Mike Morrice': 209,
    'Rob Morrison': 210,
    'Robert Morrissey': 211,
    'Glen Motz': 212,
    'Joyce Murray': 213,
    'Dan Muys': 214,
    'Yasir Naqvi': 215,
    'John Nater': 216,
    'Mary Ng': 217,
    'Taleeb Noormohamed': 218,
    'Christine Normandin': 219,
    'Robert Oliphant': 220,
    'Jeremy Patzer': 221,
    'Pierre Paul-Hus': 222,
    'Monique Pauzé': 223,
    'Ginette Petitpas Taylor': 224,
    'Louis Plamondon': 225,
    'Pierre Poilievre': 226,
    'Marcus Powlowski': 227,
    'Carla Qualtrough': 228,
    'Alain Rayes': 229,
    'Brad Redekopp': 230,
    'Scott Reid': 231,
    'Michelle Rempel Garner': 232,
    'Blake Richards': 233,
    'Anna Roberts': 234,
    'Yves Robillard': 235,
    'Pablo Rodriguez': 236,
    'Churence Rogers': 237,
    'Sherry Romanado': 238,
    'Lianne Rood': 239,
    'Anthony Rota': 240,
    'Alex Ruff': 241,
    'Ruby Sahota': 242,
    'Raj Saini': 243,
    'Harjit S. Sajjan': 244,
    'Darrell Samson': 245,
    'Randeep Sarai': 246,
    'Simon-Pierre Savard-Tremblay': 247,
    'Francis Scarpaleggia': 248,
    'Derek Sloan': 249,
    'Clifford Small': 250,
    'Francesco Sorbara': 251,
    'Gerald Soroka': 252,
    'Charles Sousa': 253,
    'Pascale St-Onge': 254,
    'Gabriel Ste-Marie': 255,
    'Warren Steinley': 256,
    'Jake Stewart': 257,
    'Filomena Tassi': 258,
    'Leah Taylor Roy': 259,
    'Luc Thériault': 260,
    'Rachael Thomas': 261,
    'Corey Tochor': 262,
    'Fraser Tolmie': 263,
    'Justin Trudeau': 264,
    'Denis Trudel': 265,
    'Ryan Turnbull': 266,
    'Tim Uppal': 267,
    'Vacant Vacant': 272,
    'Rechie Valdez': 273,
    'Tony Van Bynen': 274,
    'Adam van Koeverden': 275,
    'Tako Van Popta': 276,
    'Dan Vandal': 277,
    'Anita Vandenbeld': 278,
    'Karen Vecchio': 279,
    'Gary Vidal': 280,
    'Dominique Vien': 281,
    'Arnold Viersen': 282,
    'Julie Vignola': 283,
    'René Villemure': 284,
    'Arif Virani': 285,
    'Brad Vis': 286,
    'Kevin Vuong': 287,
    'Cathay Wagantall': 288,
    'Chris Warkentin': 289,
    'Kevin Waugh': 290,
    'Len Webber': 291,
    'Patrick Weiler': 292,
    'Jonathan Wilkinson': 293,
    'Ryan Williams': 294,
    'John Williamson': 295,
    'Jean Yip': 296,
    'Salma Zahid': 297,
    'Bonita Zarrillo': 298,
    'Bob Zimmer': 299,
    'Sameer Zuberi': 300
}
