mps="""
|   1 | Ziad                    | Aboultaif         | Edmonton Manning                                      | Conservative         | 48974.4 |,
|   2 | Scott                   | Aitchison         | Parry Sound—Muskoka                                   | Conservative         | 59686.1 |,
|   3 | Dan                     | Albas             | Central Okanagan—Similkameen—Nicola                   | Conservative         | 88703.6 |,
|   4 | John                    | Aldag             | Cloverdale—Langley City                               | Liberal              | 61739.3 |,
|   5 | Hon. Omar               | Alghabra          | Mississauga Centre                                    | Liberal              | 83666.4 |,
|   6 | Shafqat                 | Ali               | Brampton Centre                                       | Liberal              | 67930.2 |,
|   7 | Dean                    | Allison           | Niagara West                                          | Conservative         | 73597.1 |,
|   8 | Hon. Anita              | Anand             | Oakville                                              | Liberal              | 74781.2 |,
|   9 | Hon. Gary               | Anandasangaree    | Scarborough—Rouge Park                                | Liberal              | 67142.5 |,
|  10 | Charlie                 | Angus             | Timmins—James Bay                                     | New Democratic Party | 92854.4 |,
|  11 | Mel                     | Arnold            | North Okanagan—Shuswap                                | Conservative         |   74747 |,
|  12 | René                    | Arseneault        | Madawaska—Restigouche                                 | Liberal              | 46876.1 |,
|  13 | Chandra                 | Arya              | Nepean                                                | Liberal              | 66827.8 |,
|  14 | Niki                    | Ashton            | Churchill—Keewatinook Aski                            | New Democratic Party | 71309.3 |,
|  15 | Jenica                  | Atwin             | Fredericton                                           | Liberal              | 77677.2 |,
|  16 | Taylor                  | Bachrach          | Skeena—Bulkley Valley                                 | New Democratic Party | 61943.1 |,
|  17 | Vance                   | Badawey           | Niagara Centre                                        | Liberal              | 46373.8 |,
|  18 | Parm                    | Bains             | Steveston—Richmond East                               | Liberal              | 59848.3 |,
|  19 | Yvan                    | Baker             | Etobicoke Centre                                      | Liberal              | 50661.2 |,
|  20 | Tony                    | Baldinelli        | Niagara Falls                                         | Conservative         | 57718.1 |,
|  21 | John                    | Barlow            | Foothills                                             | Conservative         | 80466.9 |,
|  22 | Michael                 | Barrett           | Leeds—Grenville—Thousand Islands and Rideau Lakes     | Conservative         | 87396.5 |,
|  23 | Lisa Marie              | Barron            | Nanaimo—Ladysmith                                     | New Democratic Party | 81287.8 |,
|  24 | Xavier                  | Barsalou-Duval    | Pierre-Boucher—Les Patriotes—Verchères                | Bloc Québécois       | 59997.7 |,
|  25 | Jaime                   | Battiste          | Sydney—Victoria                                       | Liberal              | 60372.5 |,
|  26 | James                   | Bezan             | Selkirk—Interlake—Eastman                             | Conservative         | 59523.9 |,
|  27 | Hon. Marie-Claude       | Bibeau            | Compton—Stanstead                                     | Liberal              | 69033.7 |,
|  28 | Chris                   | Bittle            | St. Catharines                                        | Liberal              | 84004.1 |,
|  29 | Daniel                  | Blaikie           | Elmwood—Transcona                                     | New Democratic Party | 52670.3 |,
|  30 | Hon. Bill               | Blair             | Scarborough Southwest                                 | Liberal              | 62315.6 |,
|  31 | Yves-François           | Blanchet          | Beloeil—Chambly                                       | Bloc Québécois       | 48517.9 |,
|  32 | Maxime                  | Blanchette-Joncas | Rimouski-Neigette—Témiscouata—Les Basques             | Bloc Québécois       | 47644.3 |,
|  33 | Rachel                  | Blaney            | North Island—Powell River                             | New Democratic Party | 76384.6 |,
|  34 | Kelly                   | Block             | Carlton Trail—Eagle Creek                             | Conservative         | 75086.5 |,
|  35 | Kody                    | Blois             | Kings—Hants                                           | Liberal              | 66919.8 |,
|  36 | Hon. Randy              | Boissonnault      | Edmonton Centre                                       | Liberal              |   70346 |,
|  37 | Alexandre               | Boulerice         | Rosemont—La Petite-Patrie                             | New Democratic Party | 70514.6 |,
|  38 | Valerie                 | Bradford          | Kitchener South—Hespeler                              | Liberal              | 57343.6 |,
|  39 | Richard                 | Bragdon           | Tobique—Mactaquac                                     | Conservative         | 59705.6 |,
|  40 | John                    | Brassard          | Barrie—Innisfil                                       | Conservative         | 54293.5 |,
|  41 | Élisabeth               | Brière            | Sherbrooke                                            | Liberal              | 60288.3 |,
|  42 | Larry                   | Brock             | Brantford—Brant                                       | Conservative         | 78477.2 |,
|  43 | Alexis                  | Brunelle-Duceppe  | Lac-Saint-Jean                                        | Bloc Québécois       | 78337.6 |,
|  44 | Blaine                  | Calkins           | Red Deer—Lacombe                                      | Conservative         | 79001.8 |,
|  45 | Richard                 | Cannings          | South Okanagan—West Kootenay                          | New Democratic Party | 86109.1 |,
|  46 | Frank                   | Caputo            | Kamloops—Thompson—Cariboo                             | Conservative         | 90512.9 |,
|  47 | Ben                     | Carr              | Winnipeg South Centre                                 | Liberal              | 76225.3 |,
|  48 | Colin                   | Carrie            | Oshawa                                                | Conservative         | 63760.1 |,
|  49 | Sean                    | Casey             | Charlottetown                                         | Liberal              | 78239.2 |,
|  50 | Louise                  | Chabot            | Thérèse-De Blainville                                 | Bloc Québécois       | 63017.5 |,
|  51 | Hon. Bardish            | Chagger           | Waterloo                                              | Liberal              |   53712 |,
|  52 | George                  | Chahal            | Calgary Skyview                                       | Liberal              | 74554.8 |,
|  53 | Adam                    | Chambers          | Simcoe North                                          | Conservative         | 60813.2 |,
|  54 | Hon. François-Philippe  | Champagne         | Saint-Maurice—Champlain                               | Liberal              | 72953.3 |,
|  55 | Martin                  | Champoux          | Drummond                                              | Bloc Québécois       | 59784.6 |,
|  56 | Sophie                  | Chatel            | Pontiac                                               | Liberal              | 91943.4 |,
|  57 | Shaun                   | Chen              | Scarborough North                                     | Liberal              | 70375.4 |,
|  58 | Paul                    | Chiang            | Markham—Unionville                                    | Liberal              | 68283.5 |,
|  59 | Hon. Michael            | Chong             | Wellington—Halton Hills                               | Conservative         |   76725 |,
|  60 | Chad                    | Collins           | Hamilton East—Stoney Creek                            | Liberal              | 66046.7 |,
|  61 | Laurel                  | Collins           | Victoria                                              | New Democratic Party | 64139.2 |,
|  62 | Michael                 | Cooper            | St. Albert—Edmonton                                   | Conservative         |   73586 |,
|  63 | Serge                   | Cormier           | Acadie—Bathurst                                       | Liberal              | 71554.1 |,
|  64 | Michael                 | Coteau            | Don Valley East                                       | Liberal              | 68899.9 |,
|  65 | Gérard                  | Deltell           | Louis-Saint-Laurent                                   | Conservative         | 85732.9 |,
|  66 | Luc                     | Desilets          | Rivière-des-Mille-Îles                                | Bloc Québécois       | 66797.4 |,
|  67 | Blake                   | Desjarlais        | Edmonton Griesbach                                    | New Democratic Party | 85336.2 |,
|  68 | Sukh                    | Dhaliwal          | Surrey—Newton                                         | Liberal              | 65819.4 |,
|  69 | Anju                    | Dhillon           | Dorval—Lachine—LaSalle                                | Liberal              | 71337.5 |,
|  70 | Lena Metlege            | Diab              | Halifax West                                          | Liberal              | 56741.3 |,
|  71 | Todd                    | Doherty           | Cariboo—Prince George                                 | Conservative         | 84860.2 |,
|  72 | Han                     | Dong              | Don Valley North                                      | Independent          | 73202.3 |,
|  73 | Terry                   | Dowdall           | Simcoe—Grey                                           | Conservative         | 59650.6 |,
|  74 | Earl                    | Dreeshen          | Red Deer—Mountain View                                | Conservative         | 63887.2 |,
|  75 | Francis                 | Drouin            | Glengarry—Prescott—Russell                            | Liberal              | 69638.6 |,
|  76 | Emmanuel                | Dubourg           | Bourassa                                              | Liberal              | 54227.2 |,
|  77 | Hon. Jean-Yves          | Duclos            | Québec                                                | Liberal              | 61456.9 |,
|  78 | Terry                   | Duguid            | Winnipeg South                                        | Liberal              | 71886.1 |,
|  79 | Eric                    | Duncan            | Stormont—Dundas—South Glengarry                       | Conservative         |   80846 |,
|  80 | Hon. Kirsty             | Duncan            | Etobicoke North                                       | Liberal              | 59452.6 |,
|  81 | Julie                   | Dzerowicz         | Davenport                                             | Liberal              | 69833.7 |,
|  82 | Ali                     | Ehsassi           | Willowdale                                            | Liberal              | 53587.9 |,
|  83 | Fayçal                  | El-Khoury         | Laval—Les Îles                                        | Liberal              | 48128.5 |,
|  84 | Stephen                 | Ellis             | Cumberland—Colchester                                 | Conservative         | 78728.5 |,
|  85 | Dave                    | Epp               | Chatham-Kent—Leamington                               | Conservative         | 90370.8 |,
|  86 | Nathaniel               | Erskine-Smith     | Beaches—East York                                     | Liberal              | 84785.2 |,
|  87 | Rosemarie               | Falk              | Battlefords—Lloydminster                              | Conservative         |   46818 |,
|  88 | Ted                     | Falk              | Provencher                                            | Conservative         | 65722.9 |,
|  89 | Hon. Ed                 | Fast              | Abbotsford                                            | Conservative         | 71117.9 |,
|  90 | Hon. Greg               | Fergus            | Hull—Aylmer                                           | Liberal              | 76398.4 |,
|  91 | Michelle                | Ferreri           | Peterborough—Kawartha                                 | Conservative         | 55331.2 |,
|  92 | Andy                    | Fillmore          | Halifax                                               | Liberal              | 73143.5 |,
|  93 | Hon. Kerry-Lynne        | Findlay           | South Surrey—White Rock                               | Conservative         | 67097.8 |,
|  94 | Darren                  | Fisher            | Dartmouth—Cole Harbour                                | Liberal              | 52220.2 |,
|  95 | Peter                   | Fonseca           | Mississauga East—Cooksville                           | Liberal              | 48049.1 |,
|  96 | Hon. Mona               | Fortier           | Ottawa—Vanier                                         | Liberal              | 64355.3 |,
|  97 | Rhéal Éloi              | Fortin            | Rivière-du-Nord                                       | Bloc Québécois       | 63392.7 |,
|  98 | Peter                   | Fragiskatos       | London North Centre                                   | Liberal              | 72378.1 |,
|  99 | Hon. Sean               | Fraser            | Central Nova                                          | Liberal              | 70850.8 |,
| 100 | Hon. Chrystia           | Freeland          | University—Rosedale                                   | Liberal              | 61325.8 |,
| 101 | Hon. Hedy               | Fry               | Vancouver Centre                                      | Liberal              | 77142.8 |,
| 102 | Iqwinder                | Gaheer            | Mississauga—Malton                                    | Liberal              |   53935 |,
| 103 | Anna                    | Gainey            | Notre-Dame-de-Grâce—Westmount                         | Liberal              |   82935 |,
| 104 | Cheryl                  | Gallant           | Renfrew—Nipissing—Pembroke                            | Conservative         | 74841.8 |,
| 105 | Jean-Denis              | Garon             | Mirabel                                               | Bloc Québécois       | 72953.4 |,
| 106 | Randall                 | Garrison          | Esquimalt—Saanich—Sooke                               | New Democratic Party | 78967.4 |,
| 107 | Marie-Hélène            | Gaudreau          | Laurentides—Labelle                                   | Bloc Québécois       | 70794.9 |,
| 108 | Leah                    | Gazan             | Winnipeg Centre                                       | New Democratic Party | 74640.8 |,
| 109 | Garnett                 | Genuis            | Sherwood Park—Fort Saskatchewan                       | Conservative         | 96261.2 |,
| 110 | Mark                    | Gerretsen         | Kingston and the Islands                              | Liberal              | 58525.5 |,
| 111 | Marilène                | Gill              | Manicouagan                                           | Bloc Québécois       | 71403.4 |,
| 112 | Marilyn                 | Gladu             | Sarnia—Lambton                                        | Conservative         |   75869 |,
| 113 | Joël                    | Godin             | Portneuf—Jacques-Cartier                              | Conservative         | 65660.6 |,
| 114 | Laila                   | Goodridge         | Fort McMurray—Cold Lake                               | Conservative         | 76405.4 |,
| 115 | Hon. Karina             | Gould             | Burlington                                            | Liberal              | 75686.4 |,
| 116 | Jacques                 | Gourde            | Lévis—Lotbinière                                      | Conservative         |   54184 |,
| 117 | Tracy                   | Gray              | Kelowna—Lake Country                                  | Conservative         |   64781 |,
| 118 | Matthew                 | Green             | Hamilton Centre                                       | New Democratic Party | 84979.2 |,
| 119 | Hon. Steven             | Guilbeault        | Laurier—Sainte-Marie                                  | Liberal              |   75001 |,
| 120 | Hon. Patty              | Hajdu             | Thunder Bay—Superior North                            | Liberal              | 84506.4 |,
| 121 | Jasraj Singh            | Hallan            | Calgary Forest Lawn                                   | Conservative         |   70988 |,
| 122 | Brendan                 | Hanley            | Yukon                                                 | Liberal              | 64613.4 |,
| 123 | Ken                     | Hardie            | Fleetwood—Port Kells                                  | Liberal              | 76777.5 |,
| 124 | Lisa                    | Hepfner           | Hamilton Mountain                                     | Liberal              | 79106.5 |,
| 125 | Randy                   | Hoback            | Prince Albert                                         | Conservative         | 74831.1 |,
| 126 | Hon. Mark               | Holland           | Ajax                                                  | Liberal              | 90311.5 |,
| 127 | Anthony                 | Housefather       | Mount Royal                                           | Liberal              | 57651.1 |,
| 128 | Carol                   | Hughes            | Algoma—Manitoulin—Kapuskasing                         | New Democratic Party | 81333.2 |,
| 129 | Hon. Ahmed              | Hussen            | York South—Weston                                     | Liberal              | 64530.6 |,
| 130 | Hon. Gudie              | Hutchings         | Long Range Mountains                                  | Liberal              |   78149 |,
| 131 | Angelo                  | Iacono            | Alfred-Pellan                                         | Liberal              | 63177.2 |,
| 132 | Lori                    | Idlout            | Nunavut                                               | New Democratic Party | 67486.9 |,
| 133 | Hon. Marci              | Ien               | Toronto Centre                                        | Liberal              | 65507.6 |,
| 134 | Hon. Helena             | Jaczek            | Markham—Stouffville                                   | Liberal              | 67777.3 |,
| 135 | Matt                    | Jeneroux          | Edmonton Riverbend                                    | Conservative         | 41323.8 |,
| 136 | Gord                    | Johns             | Courtenay—Alberni                                     | New Democratic Party | 83409.7 |,
| 137 | Hon. Mélanie            | Joly              | Ahuntsic-Cartierville                                 | Liberal              | 77058.4 |,
| 138 | Yvonne                  | Jones             | Labrador                                              | Liberal              | 72022.3 |,
| 139 | Arielle                 | Kayabaga          | London West                                           | Liberal              | 49018.7 |,
| 140 | Mike                    | Kelloway          | Cape Breton—Canso                                     | Liberal              | 72697.2 |,
| 141 | Pat                     | Kelly             | Calgary Rocky Ridge                                   | Conservative         | 77164.1 |,
| 142 | Iqra                    | Khalid            | Mississauga—Erin Mills                                | Liberal              | 73058.3 |,
| 143 | Arpan                   | Khanna            | Oxford                                                | Conservative         | 61824.2 |,
| 144 | Hon. Kamal              | Khera             | Brampton West                                         | Liberal              | 72094.3 |,
| 145 | Robert                  | Kitchen           | Souris—Moose Mountain                                 | Conservative         | 55701.4 |,
| 146 | Tom                     | Kmiec             | Calgary Shepard                                       | Conservative         | 82453.9 |,
| 147 | Annie                   | Koutrakis         | Vimy                                                  | Liberal              | 62163.7 |,
| 148 | Michael                 | Kram              | Regina—Wascana                                        | Conservative         | 64868.9 |,
| 149 | Shelby                  | Kramp-Neuman      | Hastings—Lennox and Addington                         | Conservative         | 74327.4 |,
| 150 | Damien                  | Kurek             | Battle River—Crowfoot                                 | Conservative         | 59147.6 |,
| 151 | Stephanie               | Kusie             | Calgary Midnapore                                     | Conservative         | 70706.2 |,
| 152 | Irek                    | Kusmierczyk       | Windsor—Tecumseh                                      | Liberal              | 71791.5 |,
| 153 | Jenny                   | Kwan              | Vancouver East                                        | New Democratic Party | 78288.5 |,
| 154 | Hon. Mike               | Lake              | Edmonton—Wetaskiwin                                   | Conservative         | 93016.4 |,
| 155 | Marie-France            | Lalonde           | Orléans                                               | Liberal              | 67353.9 |,
| 156 | Emmanuella              | Lambropoulos      | Saint-Laurent                                         | Liberal              | 45410.5 |,
| 157 | Hon. David              | Lametti           | LaSalle—Émard—Verdun                                  | Liberal              | 66723.6 |,
| 158 | Kevin                   | Lamoureux         | Winnipeg North                                        | Liberal              | 63942.9 |,
| 159 | Melissa                 | Lantsman          | Thornhill                                             | Conservative         | 59550.9 |,
| 160 | Viviane                 | LaPointe          | Sudbury                                               | Liberal              | 69453.5 |,
| 161 | Andréanne               | Larouche          | Shefford                                              | Bloc Québécois       | 53280.3 |,
| 162 | Patricia                | Lattanzio         | Saint-Léonard—Saint-Michel                            | Liberal              | 62559.5 |,
| 163 | Stéphane                | Lauzon            | Argenteuil—La Petite-Nation                           | Liberal              | 65317.4 |,
| 164 | Philip                  | Lawrence          | Northumberland—Peterborough South                     | Conservative         | 68460.7 |,
| 165 | Hon. Dominic            | LeBlanc           | Beauséjour                                            | Liberal              | 63810.6 |,
| 166 | Hon. Diane              | Lebouthillier     | Gaspésie—Les Îles-de-la-Madeleine                     | Liberal              | 57932.9 |,
| 167 | Richard                 | Lehoux            | Beauce                                                | Conservative         | 57037.7 |,
| 168 | Sébastien               | Lemire            | Abitibi—Témiscamingue                                 | Bloc Québécois       | 93685.8 |,
| 169 | Branden                 | Leslie            | Portage—Lisgar                                        | Conservative         | 50025.4 |,
| 170 | Chris                   | Lewis             | Essex                                                 | Conservative         |   73907 |,
| 171 | Leslyn                  | Lewis             | Haldimand—Norfolk                                     | Conservative         | 78531.4 |,
| 172 | Ron                     | Liepert           | Calgary Signal Hill                                   | Conservative         | 57934.2 |,
| 173 | Joël                    | Lightbound        | Louis-Hébert                                          | Liberal              | 70943.4 |,
| 174 | Dane                    | Lloyd             | Sturgeon River—Parkland                               | Conservative         | 63745.8 |,
| 175 | Ben                     | Lobb              | Huron—Bruce                                           | Conservative         | 56827.9 |,
| 176 | Wayne                   | Long              | Saint John—Rothesay                                   | Liberal              | 67272.4 |,
| 177 | Lloyd                   | Longfield         | Guelph                                                | Liberal              | 57845.8 |,
| 178 | Tim                     | Louis             | Kitchener—Conestoga                                   | Liberal              | 67037.7 |,
| 179 | Hon. Lawrence           | MacAulay          | Cardigan                                              | Liberal              | 62350.6 |,
| 180 | Heath                   | MacDonald         | Malpeque                                              | Liberal              | 46996.3 |,
| 181 | Alistair                | MacGregor         | Cowichan—Malahat—Langford                             | New Democratic Party | 77258.8 |,
| 182 | Hon. Steven             | MacKinnon         | Gatineau                                              | Liberal              | 52018.7 |,
| 183 | Larry                   | Maguire           | Brandon—Souris                                        | Conservative         | 81198.5 |,
| 184 | Shuvaloy                | Majumdar          | Calgary Heritage                                      | Conservative         | 79115.5 |,
| 185 | James                   | Maloney           | Etobicoke—Lakeshore                                   | Liberal              | 75052.9 |,
| 186 | Richard                 | Martel            | Chicoutimi—Le Fjord                                   | Conservative         | 58424.2 |,
| 187 | Hon. Soraya             | Martinez Ferrada  | Hochelaga                                             | Liberal              | 60120.1 |,
| 188 | Brian                   | Masse             | Windsor West                                          | New Democratic Party | 83123.9 |,
| 189 | Lindsay                 | Mathyssen         | London—Fanshawe                                       | New Democratic Party | 75287.4 |,
| 190 | Bryan                   | May               | Cambridge                                             | Liberal              | 76932.7 |,
| 191 | Elizabeth               | May               | Saanich—Gulf Islands                                  | Green Party          | 88812.5 |,
| 192 | Dan                     | Mazier            | Dauphin—Swan River—Neepawa                            | Conservative         |   70776 |,
| 193 | Kelly                   | McCauley          | Edmonton West                                         | Conservative         | 63923.1 |,
| 194 | Ken                     | McDonald          | Avalon                                                | Liberal              | 82647.1 |,
| 195 | Hon. David              | McGuinty          | Ottawa South                                          | Liberal              | 55657.8 |,
| 196 | Hon. John               | McKay             | Scarborough—Guildwood                                 | Liberal              | 70222.2 |,
| 197 | Ron                     | McKinnon          | Coquitlam—Port Coquitlam                              | Liberal              | 72941.7 |,
| 198 | Greg                    | McLean            | Calgary Centre                                        | Conservative         | 73713.5 |,
| 199 | Michael                 | McLeod            | Northwest Territories                                 | Liberal              | 58048.3 |,
| 200 | Heather                 | McPherson         | Edmonton Strathcona                                   | New Democratic Party | 83163.9 |,
| 201 | Eric                    | Melillo           | Kenora                                                | Conservative         | 80496.9 |,
| 202 | Alexandra               | Mendès            | Brossard—Saint-Lambert                                | Liberal              | 50117.8 |,
| 203 | Hon. Marco              | Mendicino         | Eglinton—Lawrence                                     | Liberal              | 51467.8 |,
| 204 | Wilson                  | Miao              | Richmond Centre                                       | Liberal              | 41724.9 |,
| 205 | Kristina                | Michaud           | Avignon—La Mitis—Matane—Matapédia                     | Bloc Québécois       | 61228.6 |,
| 206 | Hon. Marc               | Miller            | Ville-Marie—Le Sud-Ouest—Île-des-Soeurs               | Liberal              | 69464.2 |,
| 207 | Hon. Rob                | Moore             | Fundy Royal                                           | Conservative         | 80680.8 |,
| 208 | Marty                   | Morantz           | Charleswood—St. James—Assiniboia—Headingley           | Conservative         | 43295.9 |,
| 209 | Mike                    | Morrice           | Kitchener Centre                                      | Green Party          | 81386.8 |,
| 210 | Rob                     | Morrison          | Kootenay—Columbia                                     | Conservative         | 83380.3 |,
| 211 | Robert                  | Morrissey         | Egmont                                                | Liberal              |   72521 |,
| 212 | Glen                    | Motz              | Medicine Hat—Cardston—Warner                          | Conservative         | 73245.5 |,
| 213 | Hon. Joyce              | Murray            | Vancouver Quadra                                      | Liberal              | 63911.4 |,
| 214 | Dan                     | Muys              | Flamborough—Glanbrook                                 | Conservative         | 61142.6 |,
| 215 | Yasir                   | Naqvi             | Ottawa Centre                                         | Liberal              | 92912.8 |,
| 216 | John                    | Nater             | Perth—Wellington                                      | Conservative         |   78678 |,
| 217 | Hon. Mary               | Ng                | Markham—Thornhill                                     | Liberal              | 50571.1 |,
| 218 | Taleeb                  | Noormohamed       | Vancouver Granville                                   | Liberal              |   89862 |,
| 219 | Christine               | Normandin         | Saint-Jean                                            | Bloc Québécois       | 69249.5 |,
| 220 | Hon. Robert             | Oliphant          | Don Valley West                                       | Liberal              | 78710.3 |,
| 221 | Jeremy                  | Patzer            | Cypress Hills—Grasslands                              | Conservative         |   47840 |,
| 222 | Pierre                  | Paul-Hus          | Charlesbourg—Haute-Saint-Charles                      | Conservative         | 66007.8 |,
| 223 | Monique                 | Pauzé             | Repentigny                                            | Bloc Québécois       | 77046.9 |,
| 224 | Hon. Ginette            | Petitpas Taylor   | Moncton—Riverview—Dieppe                              | Liberal              |   51173 |,
| 225 | Louis                   | Plamondon         | Bécancour—Nicolet—Saurel                              | Bloc Québécois       | 53548.1 |,
| 226 | Hon. Pierre             | Poilievre         | Carleton                                              | Conservative         | 33808.7 |,
| 227 | Marcus                  | Powlowski         | Thunder Bay—Rainy River                               | Liberal              | 76196.8 |,
| 228 | Hon. Carla              | Qualtrough        | Delta                                                 | Liberal              | 76257.4 |,
| 229 | Alain                   | Rayes             | Richmond—Arthabaska                                   | Independent          | 49697.5 |,
| 230 | Brad                    | Redekopp          | Saskatoon West                                        | Conservative         | 68210.1 |,
| 231 | Scott                   | Reid              | Lanark—Frontenac—Kingston                             | Conservative         | 67998.7 |,
| 232 | Hon. Michelle           | Rempel Garner     | Calgary Nose Hill                                     | Conservative         | 77916.5 |,
| 233 | Blake                   | Richards          | Banff—Airdrie                                         | Conservative         | 74263.3 |,
| 234 | Anna                    | Roberts           | King—Vaughan                                          | Conservative         | 52293.8 |,
| 235 | Yves                    | Robillard         | Marc-Aurèle-Fortin                                    | Liberal              | 61900.3 |,
| 236 | Hon. Pablo              | Rodriguez         | Honoré-Mercier                                        | Liberal              | 59736.6 |,
| 237 | Churence                | Rogers            | Bonavista—Burin—Trinity                               | Liberal              | 74244.5 |,
| 238 | Sherry                  | Romanado          | Longueuil—Charles-LeMoyne                             | Liberal              | 64289.3 |,
| 239 | Lianne                  | Rood              | Lambton—Kent—Middlesex                                | Conservative         | 71583.9 |,
| 240 | Anthony                 | Rota              | Nipissing—Timiskaming                                 | Liberal              | 69395.8 |,
| 241 | Alex                    | Ruff              | Bruce—Grey—Owen Sound                                 | Conservative         | 56594.2 |,
| 242 | Hon. Ruby               | Sahota            | Brampton North                                        | Liberal              | 56544.6 |,
| 243 | Raj                     | Saini             | Kitchener Centre                                      | Liberal              |       0 |,
| 244 | Hon. Harjit S.          | Sajjan            | Vancouver South                                       | Liberal              | 45998.2 |,
| 245 | Darrell                 | Samson            | Sackville—Preston—Chezzetcook                         | Liberal              |   44309 |,
| 246 | Randeep                 | Sarai             | Surrey Centre                                         | Liberal              | 76305.3 |,
| 247 | Simon-Pierre            | Savard-Tremblay   | Saint-Hyacinthe—Bagot                                 | Bloc Québécois       | 57019.9 |,
| 248 | Francis                 | Scarpaleggia      | Lac-Saint-Louis                                       | Liberal              | 67710.7 |,
| 249 | Derek                   | Sloan             | Hastings—Lennox and Addington                         | Independent          |       0 |,
| 250 | Clifford                | Small             | Coast of Bays—Central—Notre Dame                      | Conservative         | 73143.1 |,
| 251 | Francesco               | Sorbara           | Vaughan—Woodbridge                                    | Liberal              | 58557.1 |,
| 252 | Gerald                  | Soroka            | Yellowhead                                            | Conservative         | 57665.9 |,
| 253 | Charles                 | Sousa             | Mississauga—Lakeshore                                 | Liberal              | 66161.4 |,
| 254 | Hon. Pascale            | St-Onge           | Brome—Missisquoi                                      | Liberal              | 64029.3 |,
| 255 | Gabriel                 | Ste-Marie         | Joliette                                              | Bloc Québécois       | 78898.3 |,
| 256 | Warren                  | Steinley          | Regina—Lewvan                                         | Conservative         | 53643.1 |,
| 257 | Jake                    | Stewart           | Miramichi—Grand Lake                                  | Conservative         | 73106.1 |,
| 258 | Hon. Filomena           | Tassi             | Hamilton West—Ancaster—Dundas                         | Liberal              | 69559.4 |,
| 259 | Leah                    | Taylor Roy        | Aurora—Oak Ridges—Richmond Hill                       | Liberal              | 78703.5 |,
| 260 | Luc                     | Thériault         | Montcalm                                              | Bloc Québécois       | 61936.7 |,
| 261 | Rachael                 | Thomas            | Lethbridge                                            | Conservative         | 68381.4 |,
| 262 | Corey                   | Tochor            | Saskatoon—University                                  | Conservative         |   53488 |,
| 263 | Fraser                  | Tolmie            | Moose Jaw—Lake Centre—Lanigan                         | Conservative         | 64038.1 |,
| 264 | Right Hon. Justin       | Trudeau           | Papineau                                              | Liberal              | 58003.6 |,
| 265 | Denis                   | Trudel            | Longueuil—Saint-Hubert                                | Bloc Québécois       |   72747 |,
| 266 | Ryan                    | Turnbull          | Whitby                                                | Liberal              | 78173.2 |,
| 267 | Hon. Tim                | Uppal             | Edmonton Mill Woods                                   | Conservative         | 66593.3 |,
| 268 | Vacant                  | Vacant            | Portage—Lisgar                                        | Conservative         |       0 |,
| 269 | Vacant                  | Vacant            | Winnipeg South Centre                                 | Liberal              | 1437.44 |,
| 270 | Vacant                  | Vacant            | Notre-Dame-de-Grâce—Westmount                         | Liberal              | 4346.82 |,
| 271 | Vacant                  | Vacant            | Calgary Heritage                                      | Conservative         |       0 |,
| 272 | Vacant                  | Vacant            | Oxford                                                | Conservative         | 3941.02 |,
| 273 | Hon. Rechie             | Valdez            | Mississauga—Streetsville                              | Liberal              | 56201.5 |,
| 274 | Tony                    | Van Bynen         | Newmarket—Aurora                                      | Liberal              | 71600.9 |,
| 275 | Adam                    | van Koeverden     | Milton                                                | Liberal              | 66637.8 |,
| 276 | Tako                    | Van Popta         | Langley—Aldergrove                                    | Conservative         | 77925.5 |,
| 277 | Hon. Dan                | Vandal            | Saint Boniface—Saint Vital                            | Liberal              | 65457.7 |,
| 278 | Anita                   | Vandenbeld        | Ottawa West—Nepean                                    | Liberal              | 72007.3 |,
| 279 | Karen                   | Vecchio           | Elgin—Middlesex—London                                | Conservative         | 73964.7 |,
| 280 | Gary                    | Vidal             | Desnethé—Missinippi—Churchill River                   | Conservative         | 62896.2 |,
| 281 | Dominique               | Vien              | Bellechasse—Les Etchemins—Lévis                       | Conservative         | 52882.3 |,
| 282 | Arnold                  | Viersen           | Peace River—Westlock                                  | Conservative         | 78097.6 |,
| 283 | Julie                   | Vignola           | Beauport—Limoilou                                     | Bloc Québécois       | 73542.3 |,
| 284 | René                    | Villemure         | Trois-Rivières                                        | Bloc Québécois       | 53324.3 |,
| 285 | Hon. Arif               | Virani            | Parkdale—High Park                                    | Liberal              | 66980.7 |,
| 286 | Brad                    | Vis               | Mission—Matsqui—Fraser Canyon                         | Conservative         | 81623.2 |,
| 287 | Kevin                   | Vuong             | Spadina—Fort York                                     | Independent          | 70616.3 |,
| 288 | Cathay                  | Wagantall         | Yorkton—Melville                                      | Conservative         | 54300.9 |,
| 289 | Chris                   | Warkentin         | Grande Prairie—Mackenzie                              | Conservative         | 66218.1 |,
| 290 | Kevin                   | Waugh             | Saskatoon—Grasswood                                   | Conservative         |   70814 |,
| 291 | Len                     | Webber            | Calgary Confederation                                 | Conservative         |   76702 |,
| 292 | Patrick                 | Weiler            | West Vancouver—Sunshine Coast—Sea to Sky Country      | Liberal              | 71879.7 |,
| 293 | Hon. Jonathan           | Wilkinson         | North Vancouver                                       | Liberal              |   71937 |,
| 294 | Ryan                    | Williams          | Bay of Quinte                                         | Conservative         | 62260.7 |,
| 295 | John                    | Williamson        | New Brunswick Southwest                               | Conservative         | 81447.8 |,
| 296 | Jean                    | Yip               | Scarborough—Agincourt                                 | Liberal              | 61893.8 |,
| 297 | Salma                   | Zahid             | Scarborough Centre                                    | Liberal              | 70043.7 |,
| 298 | Bonita                  | Zarrillo          | Port Moody—Coquitlam                                  | New Democratic Party | 58745.9 |,
| 299 | Bob                     | Zimmer            | Prince George—Peace River—Northern Rockies            | Conservative         | 63865.6 |,
| 300 | Sameer                  | Zuberi            | Pierrefonds—Dollard                                   | Liberal              | 62401.5 |
"""


mp_obj = mps.split(',')
cleaned_lines = []
for obj in mp_obj:
    obj = obj[1:len(obj)-1].replace('|', ',')
    obj = obj.replace('Hon. ', '')
    cleaned_lines.append(obj)

formatted_lines = []
for line in cleaned_lines:
    obj = line[1:-1].split(',')
    cleaned_line = []
    for item in obj:
        item = item.strip()
        cleaned_line.append(item)
    formatted_lines.append(cleaned_line)

mp_lookup = {}
for entry in formatted_lines:
    id = int(entry[0])
    first_name = entry[1]
    last_name = entry[2]
    mp_lookup[f'{first_name} {last_name}'] = id


print(mp_lookup)